<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Apliteinfoamr" ignored="0" name="Zoom2u test" tests="15" failures="2" timestamp="01 Mar 2018 14:51:56 GMT" time="899.001" errors="0">
  <testcase name="beforeTest" time="37.668" classname="Test.GetQuote_Part2test"/>
  <testcase name="C1" time="20.274" classname="Test.GetQuote_Part2test"/>
  <testcase name="C13" time="64.134" classname="Test.GetQuote_Part2test"/>
  <testcase name="C14" time="47.845" classname="Test.GetQuote_Part2test">
    <failure type="java.lang.AssertionError" message="expected [Delivered by 11:00am wednesday] but found [Delivered by 8:30pm tuesday]">
      <![CDATA[java.lang.AssertionError: expected [Delivered by 11:00am wednesday] but found [Delivered by 8:30pm tuesday]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Controller.ETAInterstateTime.ETAInterstateVerify(ETAInterstateTime.java:515)
	at Controller.GetQuote_Scenarios.ETAVerifyInterstate(GetQuote_Scenarios.java:2072)
	at Test.GetQuote_Part2test.C14(GetQuote_Part2test.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- C14 -->
  <testcase name="C15" time="75.556" classname="Test.GetQuote_Part2test"/>
  <testcase name="C16" time="39.322" classname="Test.GetQuote_Part2test"/>
  <testcase name="C17" time="41.236" classname="Test.GetQuote_Part2test"/>
  <testcase name="C18" time="64.999" classname="Test.GetQuote_Part2test"/>
  <testcase name="C19" time="41.626" classname="Test.GetQuote_Part2test"/>
  <testcase name="C20" time="64.415" classname="Test.GetQuote_Part2test"/>
  <testcase name="C21" time="112.469" classname="Test.GetQuote_Part2test">
    <failure type="java.lang.AssertionError" message="expected [LQ201803016433] but found []">
      <![CDATA[java.lang.AssertionError: expected [LQ201803016433] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Controller.GetQuote_Scenarios.GetQuote_URLExtraLargeBidRequest(GetQuote_Scenarios.java:2108)
	at Test.GetQuote_Part2test.C21(GetQuote_Part2test.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- C21 -->
  <testcase name="C22" time="93.38" classname="Test.GetQuote_Part2test"/>
  <testcase name="C26" time="83.904" classname="Test.GetQuote_Part2test"/>
  <testcase name="C27" time="100.731" classname="Test.GetQuote_Part2test"/>
  <testcase name="afterTest" time="11.367" classname="Test.GetQuote_Part2test"/>
</testsuite> <!-- Zoom2u test -->
